### ISSUE TITLE
Is this Retrospring?

### ISSUE THREAD

**Issue by nilsding** [pixeldesu/ama#1]
Also, when does the WiiU app come out

**Comment by simwagner** [comment]
Oh come on. A WiiU app would be so uncool in 2017. What about an app for the Nintendo Switch? :^)

**Comment by EpicLPer** [comment]
Bitch please Vita all the way!

**Comment by nilsding** [comment]
I want to be able to read all of that in a Plan 9 file system

**Comment by pixeldesu** [comment]
I think you mean [retrospring/retrospring](https://github.com/retrospring/retrospring)!

**Comment by Elycin** [comment]
Help, retrospring is down.

**Comment by nilsding** [comment]
wtf it is up again
