### ISSUE TITLE
What's your development setup?

### ISSUE THREAD

**Issue by hugomd** [pixeldesu/ama#7]
I remember you used to use Linux for development, at least for awhile — but noticed you switched to Windows, especially when you were developing Surfbird?

What do you think are the pros and cons of each environment? Is there anything that you miss/don't miss?

**Comment by pixeldesu** [comment]
Yeah, I currently develop using Windows, and that has it's pros and cons.

As node support on Windows is really okay, I have no problems developing node/Electron (web) applications. What for example doesn't work in this case are cross-platform builds but these can be done over a build server.

What I really miss is developing Ruby and especially Ruby on Rails applications. Their setup is rather complex and Windows support is really just the Ruby part (Rails doesn't work at all). I went around this with building [Vagrant](https://www.vagrantup.com/) configurations to start VMs with Ruby environments for my projects, but as the projects got more complex this was really a pain in the ass after a while and I kinda dropped this...even though I want to come back to it soon!

So, developing on Windows is possible by now, but I'm still more of a fan of using unixoid systems for it. I often come back using my work laptop (running Ubuntu) for a lot of coding in my free time (and of course at work), so there's that!
