### ISSUE TITLE
Who are you?

### ISSUE THREAD

**Issue by BoySanic** [pixeldesu/ama#8]

**Comment by pixeldesu** [comment]
That is a really vague question, but let me try to answer it as good as I can!

I'm Andy, 20 years old frontend developer (the people that make websites look good) a small town called Rosenheim in southern Germany, Bavaria to be exact.

That's me...so, any other questions regarding who I am?

**Comment by BoySanic** [comment]
How long have you been building websites?

**Comment by pixeldesu** [comment]
Should be around 4 or 5 years by now, if not even longer!
